name: rangra_go
description: RangraGo - India's Next-Gen Ride Experience
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  socket_io_client: ^2.0.3+1
  agora_rtc_engine: ^6.1.0
  permission_handler: ^10.2.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  google_sign_in: ^6.2.1
  http: ^1.6.0
  provider: ^6.0.5
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
