name: Build APK

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: cd frontend && flutter pub get
      - run: cd frontend && flutter build apk --release
      - name: Rename APK
        run: mv frontend/build/app/outputs/flutter-apk/app-release.apk frontend/build/app/outputs/flutter-apk/RangraGo.apk
      
      - name: Cleanup Old Release
        run: |
          gh release delete latest --yes || true
          git push --delete origin latest || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: latest
          name: "RangraGo v1.0.1 (Latest)"
          files: frontend/build/app/outputs/flutter-apk/RangraGo.apk
          draft: false
          prerelease: false
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get SHA-1 Fingerprint
        run: |
          KEYSTORE_PATH=$(find ~ -name "debug.keystore" | head -n 1)
          if [ -z "$KEYSTORE_PATH" ]; then
            KEYSTORE_PATH=$(find . -name "debug.keystore" | head -n 1)
          fi
          echo "Using keystore at: $KEYSTORE_PATH"
          keytool -list -v -keystore "$KEYSTORE_PATH" -alias androiddebugkey -storepass android -keypass android | grep SHA1
        continue-on-error: true
